export default class Property {
    id?: string;

    private constructor(
        id: string | undefined,
        readonly id_extern: string,
        readonly title: string,
        readonly description: string,
        readonly category_id: string,
        readonly property_registration: string,
        readonly condominium: number,
        readonly iptu: number,
        readonly owner_id: string,
        readonly company_id: string,
        readonly constructed_area: string,
        readonly total_area: string,
        readonly sell_price: number,
        readonly rent_price: number,
        readonly objective: string,
        readonly n_bedrooms: number,
        readonly n_suites: number,
        readonly n_bathrooms: number,
        readonly n_parking: number,
        readonly n_parking_free: number,
        readonly n_washrooms: number,
        readonly n_elevators: number,
        readonly n_paviments: number,
        readonly link_tour: string,
        readonly user_id: string,
    ) {
        this.id = id;
    }

    static async createProperty(
        id_extern: string,
        title: string,
        description: string,
        category_id: string,
        property_registration: string,
        condominium: number,
        iptu: number,
        owner_id: string,
        company_id: string,
        constructed_area: string,
        total_area: string,
        sell_price: number,
        rent_price: number,
        objective: string,
        n_bedrooms: number,
        n_suites: number,
        n_bathrooms: number,
        n_parking: number,
        n_parking_free: number,
        n_washrooms: number,
        n_elevators: number,
        n_paviments: number,
        link_tour: string,
        user_id: string,
        id?: string
    ): Promise<Property> {

        return new Property(id,
            id_extern,
            title,
            description,
            category_id,
            property_registration,
            condominium,
            iptu,
            owner_id,
            company_id,
            constructed_area,
            total_area,
            sell_price,
            rent_price,
            objective,
            n_bedrooms,
            n_suites,
            n_bathrooms,
            n_parking,
            n_parking_free,
            n_washrooms,
            n_elevators,
            n_paviments,
            link_tour,
            user_id,
        );
    }
}